spring.application.name=task-service

server.port=8082

# =========================================================
# Database
# =========================================================
spring.datasource.url=jdbc:mysql://localhost:3306/task_db
spring.datasource.username=root
spring.datasource.password=Vishu@321

# =========================================================
# JPA / Hibernate
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents,retries,retryevents
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always


# =========================================================
# Employee Service Settings
# =========================================================

#employee.service.base-url=http://localhost:8081
#employee.service.connect-timeout=2s
#employee.service.read-timeout=3s
#spring.cloud.openfeign.client.config.employee-service.connect-timeout=2000
#spring.cloud.openfeign.client.config.employee-service.read-timeout=3000
spring.cloud.openfeign.client.config.employee-service.connect-timeout=500
#spring.cloud.openfeign.client.config.employee-service.read-timeout=1500

spring.cloud.openfeign.client.config.employee-service.read-timeout=5000




# =========================================================
# Eureka Client
# =========================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true


# ===============================
# Resilience4j Circuit Breaker
# ===============================

resilience4j.circuitbreaker.instances.employeeService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.employeeService.sliding-window-size=10
resilience4j.circuitbreaker.instances.employeeService.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.employeeService.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.employeeService.slow-call-duration-threshold=2s
resilience4j.circuitbreaker.instances.employeeService.slow-call-rate-threshold=50

resilience4j.circuitbreaker.instances.employeeService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.employeeService.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.employeeService.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.employeeService.register-health-indicator=true
resilience4j.circuitbreaker.instances.employeeService.event-consumer-buffer-size=20



# =================================
# Resilience4j Retry
# =================================

resilience4j.retry.instances.employeeServiceRetry.max-attempts=3
resilience4j.retry.instances.employeeServiceRetry.wait-duration=500ms

resilience4j.retry.instances.employeeServiceRetry.enable-exponential-backoff=true
resilience4j.retry.instances.employeeServiceRetry.exponential-backoff-multiplier=2

resilience4j.retry.instances.employeeServiceRetry.retry-exceptions=com.vishwambhar.microservices.task_service.exception.EmployeeServiceUnavailableException

resilience4j.retry.instances.employeeServiceRetry.ignore-exceptions=io.github.resilience4j.circuitbreaker.CallNotPermittedException,com.vishwambhar.microservices.task_service.exception.EmployeeServiceRequestExceptionEmployeeServiceRequestException

resilience4j.retry.instances.employeeServiceRetry.event-consumer-buffer-size=20


# =================================
# Resilience4j TimeLimiter
# =================================

resilience4j.timelimiter.instances.employeeServiceTimeLimiter.timeout-duration=2s
resilience4j.timelimiter.instances.employeeServiceTimeLimiter.cancel-running-future=true