spring.application.name=config-server

server.port=${SERVER_PORT:8888}

spring.cloud.config.server.git.uri=${CONFIG_REPOSITORY_URI:file:///Users/panda/Documents/Workspace/java-workspace/config-repository}
spring.cloud.config.server.git.default-label=${CONFIG_REPOSITORY_BRANCH:main}
spring.cloud.config.server.git.clone-on-start=true