CREATE DATABASE IF NOT EXISTS employee_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS task_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS notification_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
